name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest,windows-latest]
        compiler: [gcc,clang]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

    - name: Build
      run: cmake --build --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

